#pragma once

#ifdef AUDIO_ENABLE
#    define STARTUP_SONG SONG(PLANCK_SOUND)
#endif

#define MIDI_BASIC

#define ENCODER_RESOLUTION 4

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "4OMN3/Az0rBG"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60
